Sprint 3
Olga-Soloveva/react-burger pull request #6
Opened 2023-03-11 17:57 UTC by Olga-Soloveva

2023-03-11 18:48 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа 👍 
- Реализован механизм обновления токена
- При отправке данных формы если происходит ошибка - её сообщение показывается юзеру.
- Есть защита роутов от авторизованных и не авторизованных пользователей

Что необходимо исправить:
- При оформлении заказа неавторизованным пользователем происходит попытка получить данные юзера, запрос валится потому что токена нет, но потом начинается процесс обновления токена, который так же валится, потому что refresh токена тоже нет. Это лишние запросы, хорошо бы добавить проверку, что если в куках и `localStorage` нет токенов, то никаких запросов не делать.

https://user-images.githubusercontent.com/60173362/224505833-673be28d-3461-4807-9006-a92d4c622c93.mov

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-11 18:48 UTC, andryxxa93 commented on src/App.js
> +            path="/register"
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-11 18:48 UTC, andryxxa93 commented on src/components/FormPage/FormPage.js
> +export default FormPage;
**Можно лучше**

используйте для компонентов обертку React.memo, которая позволяет сократить количество лишних рендеров и улучшить производительность

Например:

```
const SomeComponent = () => {
  return (
     ...........
  );
};

export default React.memo(SomeComponent);
```

https://ru.reactjs.org/docs/react-api.html#reactmemo
https://habr.com/ru/company/plarium/blog/442116/

2023-03-12 12:20 UTC, Olga-Soloveva commented
Я решила также исправить ProtectedRoute. Не пермеудрила я его?

2023-03-12 12:28 UTC, Olga-Soloveva commented on src/App.js
> +            path="/register"
Ок, спасибо за рекомендацию.

2023-03-12 12:31 UTC, Olga-Soloveva commented on src/components/FormPage/FormPage.js
> +export default FormPage;
Правильно поняла, что это можно использовать для всех компонентов, где нет usestate, useeffect и подписки на контекст/хранилище и других вложенных компонентов?

2023-03-13 05:29 UTC, andryxxa93 commented on src/components/FormPage/FormPage.js
> +export default FormPage;
Компонент делает ререндер в трех случаях - если обновился родитель, изменился стейт или изменился пропс. `React.memo` помогает избежать рендера в случае если обновился родитель, а пропсы и стейт не изменились.

2023-03-13 05:30 UTC, andryxxa93 commented
> Я решила также исправить ProtectedRoute. Не перемудрила я с ним?

Я бы рекомендовал поместить логику в `useEffect` чтобы она не срабатывала каждый рендер.

2023-03-13 05:30 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-13 05:31 UTC, andryxxa93 commented on src/components/FormPage/FormPage.js
> +export default FormPage;
Т.е. его можно использовать везде, единственное не рекомендуется его использовать если есть `children` и это сложные компоненты, а не просто текст.

2023-03-13 13:22 UTC, Olga-Soloveva commented
> > Я решила также исправить ProtectedRoute. Не перемудрила я с ним?
> 
> Я бы рекомендовал поместить логику в `useEffect` чтобы она не срабатывала каждый рендер.

2023-03-13 13:22 UTC, closed without merging